---
- name: Patch and reboot servers
  hosts: all
      tasks:
    - include_tasks: package-yum.yml
      when:
        - (ansible_facts['distribution_major_version'] == '6') or
          (ansible_facts['distribution_major_version'] == '7')
