---
- name: Patch and reboot servers
  hosts: all
  tasks:
    - ansible.builtin.debug:
        msg: task1

    - name: Include task list in play only if the condition is true
      ansible.builtin.include_tasks: "package-{{ ansible_pkg_mgr }}.yml"
      when: ansible_pkg_mgr == 'yum'
